// ANCHOR: all
// ANCHOR: command
$ forge test --allow-failure
// ANCHOR_END: command
// ANCHOR: output
Compiling 1 files with 0.8.10
Compiler run successful

Running 1 test for test/Safe.t.sol:SafeTest
[FAIL. Counterexample: calldata=0x215a2f200000000000000000000000000000000000000001000000000000000000000000, args=[79228162514264337593543950336]] testWithdraw(uint256) (runs: 2, Î¼: 19573, ~: 19573)
Test result: FAILED. 0 passed; 1 failed; finished in 3.80ms
// ANCHOR_END: output
// ANCHOR_END: all
